import sys
import pytest
import importlib

broken = [
    # actually failing
    'bkcharts',  # import fail
    'qtawesome',
]

libs_to_import = [
    'keras',  # 'keras_base'
    'tensorflow',
    'Crypto',  # 'pycrypto',
    'IPython',
    'Levenshtein',  # 'python_levenshtein',
    'OpenSSL',  # 'pyopenssl',
    'PIL',  # 'pillow',
    'PyQt5',  # 'pyqt',
    'absl',  # 'absl-py',
    'alabaster',
    'altair',
    'anaconda_project',
    'asciitree',
    'asn1crypto',
    'astor',
    'astroid',
    'astropy',
    'atomicwrites',
    'attr',  # 'attrs',
    'babel',
    'backports',
    'backports.os',
    'backports.shutil_get_terminal_size',
    'binstar_client',  # 'anaconda_client',
    'bitarray',
    'blaze',
    'bleach',
    'bokeh',
    'boto',
    'bottleneck',
    'bs4',      # 'beautifulsoup4',
    'caffe',
    'certifi',
    'cffi',
    'chardet',
    'click',
    'cloudpickle',
    'clyent',
    'colorama',
    'conda',
    'contextlib2',
    'cryptography',
    'cv2',  # 'py_opencv',
    'cycler',
    'cython',
    'cytoolz',
    'dask',
    'datashape',
    'dateutil',  # 'python_dateutil',
    'datreant',
    'deap',
    'decorator',
    'defusedxml',
    'distributed',
    'docutils',
    'entrypoints',
    'et_xmlfile',
    'fastcache',
    'filelock',
    'flask',
    'flask_cors',
    'fuzzywuzzy',
    'gast',
    'gevent',
    'gflags',  # 'python_gflags',
    'glob2',
    'gmpy2',
    'google.protobuf',  # 'protobuf',
    'greenlet',
    'grpc',  # 'grpcio',
    'h5py',
    'hdbscan',
    'heapdict',
    'html5lib',
    'idna',
    'imageio',
    'imagesize',
    'importlib_metadata',
    'ipykernel',
    'ipyparallel',
    'ipython_genutils',
    'ipywidgets',
    'isort',
    'itsdangerous',
    'jdcal',
    'jedi',
    'jinja2',
    'jsonschema',
    'jupyter',
    'jupyter_client',
    'jupyter_console',
    'jupyter_core',
    'jupyterlab',
    'keras_applications',
    'keras_preprocessing',
    'kiwisolver',
    'lazy_object_proxy',
    'leveldb',  # 'python_leveldb',
    'libarchive',  # 'python_libarchive-c',
    'lief',  # 'py_lief',
    'llvmlite',
    'locket',
    'lxml',
    'markdown',
    'markupsafe',
    'matplotlib',
    'mccabe',
    'mistune',
    'mkl',  # 'mkl-service',
    'mkl_fft',
    'mkl_random',
    'monty',
    'more_itertools',
    'mpi4py',
    'mpmath',
    'msgpack',  # 'msgpack_python',
    'multipledispatch',
    'nb_conda',
    'nb_conda_kernels',
    'nbconvert',
    'nbformat',
    'networkx',
    'nltk',
    'nose',
    'notebook',
    'numba',
    'numexpr',
    'numpy',
    'numpydoc',
    'odo',
    'olefile',
    'openpyxl',
    'packaging',
    'palettable',
    'pandas',
    'pandocfilters',
    'parso',
    'partd',
    'path',  # 'path.py',
    'pathlib2',
    'patsy',
    'pep8',
    'pexpect',
    'pickleshare',
    'pip',
    'pkginfo',
    'pluggy',
    'ply',
    'prometheus_client',
    'prompt_toolkit',
    'psutil',
    'ptyprocess',
    'py',
    'pycodestyle',
    'pycosat',
    'pycparser',
    'pycurl',
    'pydispatch',  # 'pydispatcher',
    'pydotplus',
    'pyflakes',
    'pygments',
    'pylint',
    'pymatgen',
    'pyodbc',
    'pyparsing',
    'pytest',
    'pytz',
    'pywt',  # 'pywavelets',
    'qtconsole',
    'qtpy',
    'requests',
    'rope',
    'ruamel.yaml',
    'ruamel_yaml',
    'scandir',
    'scipy',
    'seaborn',
    'send2trash',
    'setuptools',
    'simplegeneric',
    'singledispatch',
    'sip',
    'six',
    'skimage',  # 'scikit-image',
    'sklearn',  # 'scikit-learn',
    'snowballstemmer',
    'socks',  # 'pysocks',
    'sortedcollections',
    'sortedcontainers',
    'spglib',
    'sphinx',
    'sphinxcontrib',
    'sphinxcontrib.websupport',  # 'sphinxcontrib_websupport',
    'spyder',
    'spyder_kernels',
    'sqlalchemy',
    'statsmodels',
    'stopit',
    'sympy',
    'tables',  # 'pytables',
    'tabulate',
    'tblib',
    'tensorboard',
    'termcolor',
    'terminado',
    'testpath',
    'toolz',
    'tornado',
    'tpot',
    'tqdm',
    'traitlets',
    'unicodecsv',
    'update_checker',
    'urllib3',
    'wcwidth',
    'webencodings',
    'werkzeug',
    'wheel',
    'widgetsnbextension',
    'wrapt',
    'wurlitzer',
    'xlrd',
    'xlsxwriter',
    'xlwt',
    'yaml',  # 'pyyaml',
    'zict',
    'zmq',  # 'pyzmq',
]


py3_only = [
    'backcall',  # Python 3 only
    'secretstorage',  # Python 3 only
    'typed_ast',  # py3 only
    'pytest_arraydiff',   # Python 3 only
    'pytest_doctestplus', # Python 3 only
    'pytest_openfiles',   # Python 3 only
    'pytest_remotedata',  # Python 3 only
    'jupyterlab_server',  # Python 3 only
    'keyring',   # Python 3 only
    'jeepney',  # Python 3 only
]

if sys.version_info[0] == 3:
    libs_to_import.extend(py3_only)




@pytest.mark.parametrize("lib_to_import", libs_to_import)
def test_import(lib_to_import):
    importlib.import_module(lib_to_import)
